name: Terraform Apply

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: us-east-2

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Terraform Init
        working-directory: envs/dev
        run: terraform init

      - name: Terraform Validate
        working-directory: envs/dev
        run: terraform validate

      - name: Terraform Apply
        working-directory: envs/dev
        run: |
          terraform apply \
            -var='vpc_cidr=10.0.0.0/16' \
            -var='availability_zones=["us-east-2a","us-east-2b"]' \
            -var='public_subnet_cidrs=["10.0.1.0/24","10.0.2.0/24"]' \
            -var='private_subnet_cidrs=["10.0.11.0/24","10.0.12.0/24"]' \
            -var='environment=dev' \
            -var='cluster_name=dev-eks-cluster' \
            -var='cluster_version=1.34' \
            -var='node_instance_types=["t3.small"]' \
            -var='desired_size=2' \
            -var='min_size=2' \
            -var='max_size=3' \
            -auto-approve